### ISSUE TITLE
Axios missing as a dependency in 1.0.4

### ISSUE THREAD

**Issue by emilsbee** [buckaroo-it/BuckarooSDK_Node#32]
In the release 1.0.4 Axios is missing in the dependency list so the whole package doesn't work

**Comment by Buckaroo-Rens** [comment]
@emilsbee Thanks for informing us, we will look into this straight away.

**Comment by Buckaroo-Rene** [comment]
@emilsbee,
This should be fixed now in [v1.0.5](https://github.com/buckaroo-it/BuckarooSDK_Node/releases/tag/1.0.5).
