### ISSUE TITLE
BA-345 Push URL is set as a required parameter, but should not be required

### ISSUE THREAD

**Issue by joriregter** [buckaroo-it/BuckarooSDK_Node#55]
Push URL is set as a required parameter here, but this means we can't leave push URL blank, even though it is set up in the payment plaza.

https://github.com/buckaroo-it/BuckarooSDK_Node/blob/fb8b2fccf70bf4574f045271ea6511eb2ea773c7/src/Services/PayablePaymentMethod.ts#L6C101-L6C110

**Comment by Buckaroo-Rene** [comment]
Hi @joriregter,

Thank you for reaching out about the issue you're experiencing. After discussing it with a colleague from the development team, we agree that we can remove the requirement for this parameter, allowing you to rely on the Buckaroo Plaza Push URL instead.

This task is currently in our backlog, but we aim to schedule it within the next few days before the new sprint starts to work on a solution.

**Comment by Buckaroo-Rene** [comment]
Hi @joriregter,

This issue has been scheduled for the new sprint that started today.
Usually our sprints take up to 2 weeks, but hopefully we can provide a solution earlier.

Keep you posted.
