### ISSUE TITLE
BA-639 Partial pay request for KlarnaKP is missing

### ISSUE THREAD

**Issue by gijsmin** [buckaroo-it/BuckarooSDK_Node#79]
Currently it is not supported to sent articles along the KlarnaKP pay request to make a partial capture.

**Comment by Buckaroo-Rene** [comment]
Hi @gijsmin ,

Thanks again for your PR #80 and for making the changes we suggested so quickly.
We’re planning to release it tomorrow.

**Comment by Buckaroo-Rene** [comment]
@gijsmin ,

I'm happy to confirm that the issue has been resolved in the new release, [v1.4.1.](https://github.com/buckaroo-it/BuckarooSDK_Node/releases/tag/1.4.1)

If you have any further questions or encounter additional issues, please don't hesitate to reach out.

**Comment by gijsmin** [comment]
So I tried to run some tests with my own forked and modified branch, which did sent the articles to Buckaroo but did fail without a clear error message. But now when I try to install the latest version of this package: 1.4.1, I'm not seeing the modified code? Something went wrong with the packaging?

**Comment by Buckaroo-Rene** [comment]
Hi @gijsmin ,

It seems there was an issue with the package. We're currently preparing version [1.4.2 ](https://github.com/buckaroo-it/BuckarooSDK_Node/releases/tag/1.4.1)to address this. Apologies for any inconvenience caused.
