### ISSUE TITLE
New release is missing all files on npm

### ISSUE THREAD

**Issue by dbeulen** [buckaroo-it/BuckarooSDK_Node#88]
Release 1.5.0 is missing all implementation files on NPM

See [https://www.npmjs.com/package/@buckaroo/buckaroo_sdk?activeTab=code](https://www.npmjs.com/package/@buckaroo/buckaroo_sdk?activeTab=code)

**Comment by ShuCh3n** [comment]
Yes! Thanks for bringing this to our attention. We are working on a fix.

**Comment by ShuCh3n** [comment]
It should be fixed now. https://www.npmjs.com/package/@buckaroo/buckaroo_sdk/v/1.5.2?activeTab=code

Once again thanks for bringing this to our attention.
